### ISSUE TITLE
如果以jar方式启动无法读取rsa证书文件

### ISSUE THREAD

**Issue by thankuu** [Zoctan/spring-boot-api-seedling#4]
原代码(无法读取):
>
     private byte[] replaceAndBase64Decode(
     final String file, final String headReplace, final String tailReplace) throws Exception {
        // 从 classpath:resources/ 中加载资源
        final ResourceLoader loader = new DefaultResourceLoader();
        final File f = loader.getResource(file).getFile();
        final FileInputStream fis = new FileInputStream(f);
        final DataInputStream dis = new DataInputStream(fis);
        final byte[] keyBytes = new byte[(int) f.length()];
        dis.readFully(keyBytes);
        dis.close();

        final String keyPEM =
           new String(keyBytes).replace(headReplace, "").trim().replace(tailReplace, "").trim();

       return Base64.decodeBase64(keyPEM);
  }

更改后的代码：
> 
     private byte[] replaceAndBase64Decode(
            final String file, final String headReplace, final String tailReplace) throws Exception {
        // 从 classpath:resources/ 中加载资源
        final ClassPathResource resource = new ClassPathResource(file);
        final InputStream fis = resource.getInputStream();
        final byte[] keyBytes = IOUtils.toByteArray(fis);
        final String keyPEM =
                new String(keyBytes).replace(headReplace, "").trim().replace(tailReplace, "").trim();

        return Base64.decodeBase64(keyPEM);
    }

**Comment by Zoctan** [comment]
@thankuu jar没有测过，使用war没有问题，新更新的加了可以直接用字符串公私钥的rsa配置
