### ISSUE TITLE
entity 主键生成问题

### ISSUE THREAD

**Issue by lpc001** [Zoctan/spring-boot-api-seedling#5]
将entity主键生成方式改为
`@GeneratedValue(strategy = GenerationType.TABLE, generator = "account_id_gen" )`
`@TableGenerator(name = "account_id_gen", table = "generator_table", pkColumnName = "gen_name", valueColumnName = "next_val", pkColumnValue = "user_account_id_gen", initialValue = 1000, allocationSize = 1 )`
启动的时候报错：
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountMapper'  AccountMapper.class]: Invocation of init method failed; nested exception is tk.mybatis.mapper.MapperException: tk.mybatis.mapper.MapperException: tk.mybatis.mapper.MapperException: userAccountId - 该字段@GeneratedValue配置只允许以下几种形式:
1.useGeneratedKeys的@GeneratedValue(generator=\"JDBC\")  
2.类似mysql数据库的@GeneratedValue(strategy=GenerationType.IDENTITY[,generator="Mysql"])`

**Comment by Zoctan** [comment]
这个是mapper的问题，建议去mapper的issue里提问
