### ISSUE TITLE
jwt token有效问题？

### ISSUE THREAD

**Issue by mgliang** [Zoctan/spring-boot-api-seedling#7]
感谢作者的分享，很优秀的项目 。想问下 jwt token失效之后怎么在请求获取token， 如果用在生产这块逻辑怎么做呢？

**Comment by Zoctan** [comment]
目前没有添加token失效后的请求controller，常见的解决有2个：
1、在线时自动延长token时效【无效】。因为使用了jwt，已经设置了过期时间，除非是在快要过期时，自动签发新的token让前端保存。这又涉及到前端如何检查token过期时间问题，比较麻烦。
2、token过期，前端获取到的返回值是过期相关的code，前端路由自动跳转到登陆界面让用户重新登陆，这个比较方便。
